### ISSUE TITLE
请教个问题：

### ISSUE THREAD

**Issue by gitldy1013** [JermineHu/ws_rtsp#1]
runsv nginx: fatal: unable to start ./run: access denied
runsv nginx: fatal: unable to start log/./run: access denied
runsv ws_rtsp: fatal: unable to start log/./run: access denied
runsv ws_rtsp: fatal: unable to start ./run: access denied
runsv nginx: fatal: unable to start ./run: access denied
runsv nginx: fatal: unable to start log/./run: access denied
runsv ws_rtsp: fatal: unable to start log/./run: access denied
runsv ws_rtsp: fatal: unable to start ./run: access denied
runsv nginx: fatal: unable to start ./run: access denied
runsv nginx: fatal: unable to start log/./run: access denied
容器中一直出现这个问题 访问权限不足 请教一下朋友 这个怎么解决?

**Comment by JermineHu** [comment]
当时构建镜像时采用的runit作为docker容器的进程管理工具，当前错误应该是权限问题，可以尝试将runit修改为dumb-init ，可以参照： https://github.com/Yelp/dumb-init 或者 https://www.iamle.com/archives/tag/runit

**Comment by gitldy1013** [comment]
ok
